config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :providers
  root 'providers#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/provider.rb
class Provider < ApplicationRecord
  attribute :isp_email,:validate => /^([a-zA-Z0-9_.+-])+\@(([a-zA-Z0-9-])+\.)+([a-zA-Z0-9]{2,4})+$/
  validates_presence_of :name, :website, :description, :isp_email, :image, :rating, :contact_no, :max_speed, :lowest_price
  
  TYPE_OF_FILTER = {
  	'Featured' => 'created_at',
  	'Price low to high' => 'lowest_price', 
  	'Price high to low'=> 'lowest_price DESC', 
  	'Rating low to high'=> 'rating', 
  	'Rating high to low'=> 'rating DESC'
  }.freeze

  def blank_stars
    5 - rating.to_i
  end

 
  def self.get_order_by_clause(filter)
  	TYPE_OF_FILTER[filter.to_s]
  end
  
  def self.search(search)
    where("lower(name) LIKE ? OR lowest_price = ?", "%#{search.downcase}%", search.to_i)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
     :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/providers_controller.rb
class ProvidersController < ApplicationController 
  before_action :set_provider, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :update, :destroy, :new, :create]
	def index
	  if params[:search].present?
	  	@providers = Provider.search(params[:search]).order('created_at')
	  elsif params[:filter].present?
	    order_clause = Provider.get_order_by_clause(params[:filter])
	    @providers = Provider.all.order(order_clause)
	  else
	  	@providers = Provider.all.order('created_at')
	  end

	end

	def new
		@provider = Provider.new()
	end
	
	def create
		@provider = Provider.new(provider_params)
		if @provider.save
			flash.now[:sucess] = "Vollaasss added"
		  redirect_to @provider 
		else
			redirect_to 'new'
		end
	end
	
	def edit
	end

	def show
	end
	
	def update
    if @provider.update(provider_params)
      redirect_to @provider
    else
      render 'edit'
    end
	end
 
    def destroy
      @provider.destroy
      redirect_to providers_path
    end
  
  private

  def set_provider
    @provider = Provider.find(params[:id])
  end
  
  def provider_params
    params.require(:provider).permit(:name,:description, :isp_email, :rating, :contact_no, :website, :image, :max_speed, :lowest_price)
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %title KnowISP
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body 
    %section.hero.is-primary.is-bold
      .hero-head
        %nav.navbar
          .container
            .navbar-brand
        #navbarMenuHeroA.navbar-menu
          .navbar
            %h2.title
              = link_to 'Home', root_path, class: "navbar-item"
            -if user_signed_in?
              %h1.title
                = link_to "Create New ISP", new_provider_path, class:"navbar-item"
              %h1.title
                = link_to 'Edit profile', edit_user_registration_path, class:"navbar-item"
              %h1
                .title
                  = link_to "Logout", destroy_user_session_path, method: :delete, class: 'navbar-item'
                .subtitle.is-5 ( #{current_user.email}  )
            -else  
              .navbar
                %h1.title
                  = link_to "Sign up", new_user_registration_path, class:"navbar-item"
              .navbar
                %h1.title
                  = link_to "Login", new_user_session_path, class:"navbar-item"
    %section.hero.is-primary.is-bold.hero-footer
      .container
        .has-text-centered
          %h1.title
            = yield :page_title
    - if notice
      %p.notification.is-success.is-light{:role => "alert"}= notice
    - if alert
      %p.notification.is_danger.is-light{:role => "alert"}= alert
    = yield

app/views/providers/_form.html.haml
.section
  = simple_form_for @provider do |f|
    .field.control
      = f.error_notification id: 'user_error_message', class: 'form_error'
    .field.control
      = f.input :name, input_html: { class: 'input', required: true }, wrapper: false, label_html: { class: 'label'}, placeholder:  "Name"
    .field.control
      = f.input :isp_email, label: "Email", input_html: { class: 'input'}, wrapper: false, label_html: { class: 'label' }, placeholder: 'username@domain.com'
    .field.control
      = f.input :contact_no, label: "Contact Number", as: :numeric , input_html: { class: 'input'}, wrapper: false,label_html: { class: 'label' }, placeholder: '9999999999'
    .field.control
      =f.input :rating, input_html: {type: 'range',step: 1,  min: 0, max: 5}, wrapper: false, label_html: { class: 'label'}, :type => "range"
    .field.control
      = f.input :website, label: "Website Url",input_html: { class: 'input'}, wrapper: false, label_html: { class: 'label' }, placeholder: 'http://'
    .field.control
      = f.input :image, label:"Image Link",input_html: { class: 'input'}, wrapper: false, label_html: { class: 'label' }, placeholder: 'http://'
    .field.control
      = f.input :max_speed, label: "Maximum BandWidth (Mbps) ", as: :numeric, input_html: { class: 'input'}, wrapper: false, label_html: { class: 'label' }, placeholder: '10'
    .field.control
      -unit = MaxrvuTest::Application.config.currency_symbol
      = f.input :lowest_price, label: "Lowest Price(#{unit}) ", as: :numeric, input_html: { class: 'input'}, wrapper: false, label_html: { class: 'label' }, placeholder: "500#{unit}"
    .field.control 
      = f.input :description, input_html: { class: 'textarea' }, wrapper: false, label_html: { class: 'label' }, placeholder: 'Tell us more about you...'
    = f.button :submit, class: 'button is-primary'

app/views/providers/_provider_form.html.haml
%link{:href => "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css", :rel => "stylesheet"}
  
  .section.container
    .level-item.left
      %p.subtitle.is-5
        -if @providers.count > 0
          %strong Total #{@providers.count} Providers
    .level-item.level-right
      = form_tag '', method:'GET' do  
        .level-item
          .field.has-addons
            %p.control  
              %input.input{:placeholder => "Find a Internet Provider", :type => "text", class: 'search', required: 'true', name: 'search', value: params[:search]}
            %p.control
              %button.button
                Search
    .level-item.level-right  
      = form_tag '', :method => 'get' do
        .level-item.right
          .control
            .select.is-primary
              .select
                = select_tag(:filter, options_for_select(Provider::TYPE_OF_FILTER.keys, selected: params[:filter].presence || 'Featured'), onchange: 'this.form.submit();')
  .section.container
    -if @providers.count==0 
      %figure
        %img{alt: "Image Processing", src: 'https://vanmak.in/assets/images/no_result.gif', height: "700",width:"1000"}
    - @providers.each do |provider|
      .card.card-content
        %table.table.is-hoverable.is-striped.is-fullwidth
          %tr
            %td{align:"left"}
              %a{href: "providers/#{provider.id}", target: "_blank"}  
                %figure.image.is-128x128
                  %img{alt: "Image Processing", src: provider.image.to_s}
            %td{align:"center"}
              .title.is-4
                = link_to provider.name, provider
              .subtitle.is-6 #{MaxrvuTest::Application.config.currency_symbol}#{provider.lowest_price.to_i}
            %td{align:"right"}
              - provider.rating.to_i.times do
                %span.fa.fa-star{:style => "color:orange"}
              - provider.blank_stars.times do
                %span.fa.fa-star
              .subtitle.is-6=provider.created_at.strftime('%b%Y')        

        .content
          .Title.is-5{style: 'color:black;font-size:1.1em;'} Maximum Bandwidth: #{provider.max_speed.to_f} Mbps
        .content
          .Title.is-5 
            %a.b{:href => provider.website} #{provider.website}
        .content
          - if provider.description.length > 250
            = truncate(provider.description, length: 250)
            = link_to '...Read more', provider
          - else
            = provider.description

app/views/providers/edit.html.haml
-content_for :page_title, 'Edit Provider Details'
=render 'form'

app/views/providers/index.html.haml
- content_for :page_title,  "Index"
=render 'provider_form'

app/views/providers/new.html.haml
- content_for :page_title, 'Create a new Provider'
=render 'form'

app/views/providers/show.html.haml
%link{:href => "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css", :rel => "stylesheet"}
- content_for :page_title, @provider.name
%section.section
  .container
    %article.media
      %figure.media-left
        %a{href: @provider.website, target: "_blank"}
          %figure.image.is-128x128
            %img{alt: "Image Processing", src: @provider.image.to_s}
      .media-content
        .content.level-left
          .level-item
            %strong
              - @provider.rating.to_i.times do
                %span.fa.fa-star{:style => "color:orange"}
              - @provider.blank_stars.times do
                %span.fa.fa-star
        %p
          %strong=@provider.isp_email              
        %p
          %strong=@provider.contact_no
        %p
          %a.b{:href => @provider.website} Visit Website
        %p  
          %small=@provider.created_at.strftime('%b%Y')  
      %nav.level.level-left
        %p.level-item
          = link_to "Edit", edit_provider_path(@provider), class:"button"
        %p.level-item
          = link_to "Delete", provider_path(@provider),method: :delete,data: { confirm: "Are you sure?" }, class:"button is-danger"
    %hr
    .content
      .label.subtitle.is-5 Amount
      .subtitle.is-5 Our Lowerst Price is #{MaxrvuTest::Application.config.currency_symbol}#{@provider.lowest_price.to_i}
    .content
      .label.subtitle.is-5 Speed
      .subtitle.is-5 Get Maximum bandwidth upto #{@provider.max_speed}
    .content
      .label.subtitle.is-5 Description
      = @provider.description